// Salkkarit.Models.soundPathCollections.push([
// "sounds/aaro ja eero/ai niinkö.wav",
// "sounds/aaro ja eero/ainiinhanseolikinmäkäynviinakaupas.wav",
// "sounds/aaro ja eero/ainiinkö.wav",
// "sounds/aaro ja eero/chichichichileläistä.wav",
// "sounds/aaro ja eero/eikaiolluliiankuoppanen.wav",
// "sounds/aaro ja eero/heijenni.wav",
// "sounds/aaro ja eero/housutjakengätpois.wav",
// "sounds/aaro ja eero/hyvä sönkkö.wav",
// "sounds/aaro ja eero/istu toho.wav",
// "sounds/aaro ja eero/jootottakai.wav",
// "sounds/aaro ja eero/kauniitauniabeibe.wav",
// "sounds/aaro ja eero/kelpaakotämä.wav",
// "sounds/aaro ja eero/löytyiskösulla.wav",
// "sounds/aaro ja eero/maltantuskinodottaa 2.wav",
// "sounds/aaro ja eero/maltantuskinodottaa.wav",
// "sounds/aaro ja eero/mihinsäpyrit.wav",
// "sounds/aaro ja eero/minäjajennimuutetaan.wav",
// "sounds/aaro ja eero/mitädödöäsäkäytät 2.wav",
// "sounds/aaro ja eero/mitädödöäsäkäytät.wav",
// "sounds/aaro ja eero/mitässänytoikeinhöpsit 2.wav",
// "sounds/aaro ja eero/mitässänytoikeinhöpsit.wav",
// "sounds/aaro ja eero/mitäsähaluatmustamihinmeollaanmenossa.wav",
// "sounds/aaro ja eero/mummelia.wav",
// "sounds/aaro ja eero/mäenymmärräminnesäpyrittällä.wav",
// "sounds/aaro ja eero/mäkukuvittelin.wav",
// "sounds/aaro ja eero/mäsanoinkijosmäsöisin.wav",
// "sounds/aaro ja eero/mäsatutansua.wav",
// "sounds/aaro ja eero/niin.wav",
// "sounds/aaro ja eero/noeisitte.wav",
// "sounds/aaro ja eero/nytsealkaasönkkö.wav",
// "sounds/aaro ja eero/onkonälkä.wav",
// "sounds/aaro ja eero/pitkästäaikaa.wav",
// "sounds/aaro ja eero/pusipusi.wav",
// "sounds/aaro ja eero/sehänmeniaikahyvin.wav",
// "sounds/aaro ja eero/seselviääsullekyllä.wav",
// "sounds/aaro ja eero/sopivan tulista.wav",
// "sounds/aaro ja eero/surkeatapaus.wav",
// "sounds/aaro ja eero/säoletihanhullu.wav",
// "sounds/aaro ja eero/SÖNKKÖ!.wav",
// "sounds/aaro ja eero/tajuatkomitensäälittävältä.wav",
// "sounds/aaro ja eero/takki ja paita pois.wav",
// "sounds/aaro ja eero/todellasurkeatapaus.wav",
// "sounds/aaro ja eero/turpakiinni.wav",
// "sounds/aaro ja eero/turpakiinnisönkkö.wav",
// "sounds/aaro ja eero/tyhjennäs taskus toho pöydälle.wav",
// "sounds/aaro ja eero/tämä.wav",
// "sounds/aaro ja eero/täällätuoksuu.wav",
// "sounds/aaro ja eero/valkosipuli.wav",
// "sounds/aaro ja eero/valkosipulia.wav",
// "sounds/aaro ja eero/ymmärrätkö.wav",
// "sounds/aaro ja eero/ähhhh.wav",
// "sounds/aaro ja eero/äläsnytjenniviitsi.wav",
// "sounds/aaro ja eero/älästeemitääntyperääettei.wav"
// ]);

// Salkkarit.Models.soundPathCollections.push([
// "sounds/Aaro-Eero 2/eräs viisas mies on sanonu.wav",
// "sounds/Aaro-Eero 2/eräs viisas mies on sanonu2.wav",
// "sounds/Aaro-Eero 2/hyvä.wav",
// "sounds/Aaro-Eero 2/Hän on erittäin vaarallinen, karannut sairaalasta.wav",
// "sounds/Aaro-Eero 2/kyllä jenni ymmärtää.wav",
// "sounds/Aaro-Eero 2/mitäs sitte keksitään.wav",
// "sounds/Aaro-Eero 2/mun on ihan pakko sanoa että sä olet yks hienoimmista ihmisistä joita mä olen koskaan tavannu.wav",
// "sounds/Aaro-Eero 2/Mä kuristin Lauraa ihan tosissani kurkusta.wav",
// "sounds/Aaro-Eero 2/mä oon päättäny olla sepon oppipoika.wav",
// "sounds/Aaro-Eero 2/No uskokaa nyt se nainen uhkas mua puukolla.wav",
// "sounds/Aaro-Eero 2/Oli puukko.wav",
// "sounds/Aaro-Eero 2/oon samaa mieltä.wav",
// "sounds/Aaro-Eero 2/seppo taalasmaa.wav",
// "sounds/Aaro-Eero 2/sä olet huono ja susta ei ole mihinkään.wav",
// "sounds/Aaro-Eero 2/Tämä nainen on Laura Kiviranta.wav",
// "sounds/Aaro-Eero 2/Täällä se Laura jossain kulkee puukko hallussa.wav",
// "sounds/Aaro-Eero 2/vaikka pätkätöitä ja....wav",
// "sounds/Aaro-Eero 2/voisitko ottaa vakavamman ilmeen.wav",
// "sounds/Aaro-Eero 2/voisitko ottaa vähä sellasen.wav",
// "sounds/Aaro-Eero 2/öö tota.wav",
// "sounds/Aaro-Eero 2/öö tota2.wav"
// ]);

// Salkkarit.Models.soundPathCollections.push([
// "sounds/aki/et sä parempaa keksi.wav",
// "sounds/aki/hauska tutustua ja tervetuloa kahvilaan.wav",
// "sounds/aki/kahvilassa.wav",
// "sounds/aki/kaupassa.wav",
// "sounds/aki/markus.wav",
// "sounds/aki/moooi.wav",
// "sounds/aki/niinku mua huvittais vittu jäädä tänne.wav",
// "sounds/aki/näätsä se yrittää estää keinolla millä hyvänsä meiän avioliiton.wav",
// "sounds/aki/saatana lopeta toi pelleily.wav",
// "sounds/aki/supermarketissa.wav"
// ]);

// Salkkarit.Models.soundPathCollections.push([
// "sounds/hokkanen/eiku.wav",
// "sounds/hokkanen/eiootietoo.wav",
// "sounds/hokkanen/hapokasajatus.wav",
// "sounds/hokkanen/hapokashokkanen 2.wav",
// "sounds/hokkanen/hapokashokkanen.wav",
// "sounds/hokkanen/hokka yhdessäillassa.wav",
// "sounds/hokkanen/hokka-alko.wav",
// "sounds/hokkanen/hokka-eeeivielä.wav",
// "sounds/hokkanen/hokka-eijaksaenem.wav",
// "sounds/hokkanen/hokka-eikaoo.wav",
// "sounds/hokkanen/hokka-eiookoskaauskonu.wav",
// "sounds/hokkanen/hokka-eioovieläruvennu.wav",
// "sounds/hokkanen/hokka-eipysty.wav",
// "sounds/hokkanen/hokka-eipystyjuomaan.wav",
// "sounds/hokkanen/hokka-eisejarkevaaole.wav",
// "sounds/hokkanen/hokka-elamantavasta.wav",
// "sounds/hokkanen/hokka-hampaat.wav",
// "sounds/hokkanen/hokka-hapokasta.wav",
// "sounds/hokkanen/hokka-happopitoista.wav",
// "sounds/hokkanen/hokka-harrastan.wav",
// "sounds/hokkanen/hokka-isostasuppilosta.wav",
// "sounds/hokkanen/hokka-joo.wav",
// "sounds/hokkanen/hokka-juoma.wav",
// "sounds/hokkanen/hokka-juu.wav",
// "sounds/hokkanen/hokka-juulähetään.wav",
// "sounds/hokkanen/hokka-juuolen.wav",
// "sounds/hokkanen/hokka-kauhistuttavaajatus.wav",
// "sounds/hokkanen/hokka-kehareiden.wav",
// "sounds/hokkanen/hokka-khyllä.wav",
// "sounds/hokkanen/hokka-kohtajo.wav",
// "sounds/hokkanen/hokka-kolmessa.wav",
// "sounds/hokkanen/hokka-kuminaamareita.wav",
// "sounds/hokkanen/hokka-kyllaolen.wav",
// "sounds/hokkanen/hokka-kyllaon.wav",
// "sounds/hokkanen/hokka-kylläsekionjoskus.wav",
// "sounds/hokkanen/hokka-lampimampaa.wav",
// "sounds/hokkanen/hokka-letkunkautta.wav",
// "sounds/hokkanen/hokka-litraa.wav",
// "sounds/hokkanen/hokka-maailmantaisuomen.wav",
// "sounds/hokkanen/hokka-manne.wav",
// "sounds/hokkanen/hokka-menee.wav",
// "sounds/hokkanen/hokka-menossa.wav",
// "sounds/hokkanen/hokka-minunnäköisiä.wav",
// "sounds/hokkanen/hokka-mmm.wav",
// "sounds/hokkanen/hokka-mullon.wav",
// "sounds/hokkanen/hokka-naama.wav",
// "sounds/hokkanen/hokka-nemustuu.wav",
// "sounds/hokkanen/hokka-nii se on tarkotus.wav",
// "sounds/hokkanen/hokka-no ihan.wav",
// "sounds/hokkanen/hokka-noen.wav",
// "sounds/hokkanen/hokka-nooo.wav",
// "sounds/hokkanen/hokka-nosetuliyllätyksenä.wav",
// "sounds/hokkanen/hokka-nosillonkusita.wav",
// "sounds/hokkanen/hokka-nyt.wav",
// "sounds/hokkanen/hokka-nyttultiin.wav",
// "sounds/hokkanen/hokka-parikertaaviikossa.wav",
// "sounds/hokkanen/hokka-puol.wav",
// "sounds/hokkanen/hokka-puoltoista.wav",
// "sounds/hokkanen/hokka-seisoopoydalla.wav",
// "sounds/hokkanen/hokka-sekuntiin.wav",
// "sounds/hokkanen/hokka-senäkyyvatsan.wav",
// "sounds/hokkanen/hokka-setulijoautomatkalla.wav",
// "sounds/hokkanen/hokka-siinamenevat.wav",
// "sounds/hokkanen/hokka-suppilosta.wav",
// "sounds/hokkanen/hokka-terveh.wav",
// "sounds/hokkanen/hokka-terveys.wav",
// "sounds/hokkanen/hokka-terveysjahampaat.wav",
// "sounds/hokkanen/hokka-tiedossa.wav",
// "sounds/hokkanen/hokka-tommosenniinkun.wav",
// "sounds/hokkanen/hokka-tunnissa.wav",
// "sounds/hokkanen/hokka-tämä.wav",
// "sounds/hokkanen/hokka-uintiaharrastan.wav",
// "sounds/hokkanen/hokka-viiteen.wav",
// "sounds/hokkanen/hokka-yhdessa.wav",
// "sounds/hokkanen/hokkane2.wav",
// "sounds/hokkanen/hokkanen-pöydällä.wav",
// "sounds/hokkanen/juont-ekspelottanuettätääpyörä.wav",
// "sounds/hokkanen/juont-katotaakuinkakauankestää.wav",
// "sounds/hokkanen/juont-mitäsäluuletkauansiinämenee.wav",
// "sounds/hokkanen/juont-nytmetehääntäävarsinainenennätys.wav",
// "sounds/hokkanen/juont-päänahkaolitulessa.wav",
// "sounds/hokkanen/juont-saaiottehätempun.wav",
// "sounds/hokkanen/juont-senjalkeentehaanennatys.wav",
// "sounds/hokkanen/juont-seonsiellä.wav",
// "sounds/hokkanen/juont-siinaolimenoajameininkiä.wav",
// "sounds/hokkanen/juont-sootshowmies.wav",
// "sounds/hokkanen/juont-takarenkaan.wav",
// "sounds/hokkanen/juont-tietenki.wav",
// "sounds/hokkanen/juont-wanha.wav",
// "sounds/hokkanen/juont-äskentakarengasoli.wav",
// "sounds/hokkanen/juontaja-brasiliaa.wav",
// "sounds/hokkanen/juontaja-eihäntätävoipullollistavetää.wav",
// "sounds/hokkanen/juontaja-eipysty.wav",
// "sounds/hokkanen/juontaja-hahahahaha.wav",
// "sounds/hokkanen/juontaja-hahahahaha2.wav",
// "sounds/hokkanen/juontaja-hahahahaha3.wav",
// "sounds/hokkanen/juontaja-hahahahaha4.wav",
// "sounds/hokkanen/juontaja-happopitoista.wav",
// "sounds/hokkanen/juontaja-harmaitahiuksia.wav",
// "sounds/hokkanen/juontaja-hienostisanottu.wav",
// "sounds/hokkanen/juontaja-hitaampi.wav",
// "sounds/hokkanen/juontaja-hokkane.wav",
// "sounds/hokkanen/juontaja-holliokkanen.wav",
// "sounds/hokkanen/juontaja-hyvätkatsojat.wav",
// "sounds/hokkanen/juontaja-kakstuhattakolmekymmentä.wav",
// "sounds/hokkanen/juontaja-kivakukävit.wav",
// "sounds/hokkanen/juontaja-kokiksenjuoja.wav",
// "sounds/hokkanen/juontaja-kokiksenjuojakaveri.wav",
// "sounds/hokkanen/juontaja-kokista.wav",
// "sounds/hokkanen/juontaja-kolaolli.wav",
// "sounds/hokkanen/juontaja-kröhömmm.wav",
// "sounds/hokkanen/juontaja-lihava.wav",
// "sounds/hokkanen/juontaja-mikäslipputääon.wav",
// "sounds/hokkanen/juontaja-mita.wav",
// "sounds/hokkanen/juontaja-muistatkomikätääoli.wav",
// "sounds/hokkanen/juontaja-noniinpäon.wav",
// "sounds/hokkanen/juontaja-nytkävinäin.wav",
// "sounds/hokkanen/juontaja-nytmennäänmainoskatkolle.wav",
// "sounds/hokkanen/juontaja-nyttuliuusennätys.wav",
// "sounds/hokkanen/juontaja-onkotullunimestäpaljonkettuilua.wav",
// "sounds/hokkanen/juontaja-onkstosmitääjärkee.wav",
// "sounds/hokkanen/juontaja-onkstuttukaveri.wav",
// "sounds/hokkanen/juontaja-onneksolkoon.wav",
// "sounds/hokkanen/juontaja-onneksolkoon2.wav",
// "sounds/hokkanen/juontaja-onneksolkoon3.wav",
// "sounds/hokkanen/juontaja-ootsävalmis.wav",
// "sounds/hokkanen/juontaja-planbeesysteemi.wav",
// "sounds/hokkanen/juontaja-päänahka.wav",
// "sounds/hokkanen/juontaja-päänahkaa.wav",
// "sounds/hokkanen/juontaja-rami.wav",
// "sounds/hokkanen/juontaja-sanotaanvarmaanetta.wav",
// "sounds/hokkanen/juontaja-satakakskytviismiltästääkuulostaa.wav",
// "sounds/hokkanen/juontaja-saunotaan.wav",
// "sounds/hokkanen/juontaja-sekunti.wav",
// "sounds/hokkanen/juontaja-seolimunmoka.wav",
// "sounds/hokkanen/juontaja-showmies.wav",
// "sounds/hokkanen/juontaja-showmies2.wav",
// "sounds/hokkanen/juontaja-silmätkiinni.wav",
// "sounds/hokkanen/juontaja-sisaantulo.wav",
// "sounds/hokkanen/juontaja-stuntmies.wav",
// "sounds/hokkanen/juontaja-suomenkansa.wav",
// "sounds/hokkanen/juontaja-säootjusttehnyuudensuomen.wav",
// "sounds/hokkanen/juontaja-säootvarmastikyllätehnytän.wav",
// "sounds/hokkanen/juontaja-taitoajaja.wav",
// "sounds/hokkanen/juontaja-teeveessa.wav",
// "sounds/hokkanen/juontaja-tehtaalla.wav",
// "sounds/hokkanen/juontaja-terve2.wav",
// "sounds/hokkanen/juontaja-tervetuloatakas.wav",
// "sounds/hokkanen/juontaja-tonlihavampi.wav",
// "sounds/hokkanen/juontaja-tositulista.wav",
// "sounds/hokkanen/juontaja-tuhatseittemänsataa.wav",
// "sounds/hokkanen/juontaja-tämmönentota.wav",
// "sounds/hokkanen/juontaja-upeasuoritus.wav",
// "sounds/hokkanen/juontaja-vaikuttavaa.wav",
// "sounds/hokkanen/juontajarepee.wav",
// "sounds/hokkanen/kokis on.wav",
// "sounds/hokkanen/kolmessa illassa 2.wav",
// "sounds/hokkanen/kylla! 2.wav",
// "sounds/hokkanen/kyllapystyy-eikaikuu.wav",
// "sounds/hokkanen/minuutissa.wav",
// "sounds/hokkanen/onnistu.wav",
// "sounds/hokkanen/pullo on tyhjä.wav",
// "sounds/hokkanen/sukulaiset.wav",
// "sounds/hokkanen/terveterve.wav",
// "sounds/hokkanen/yllä.wav",
// "sounds/hokkanen/ähh.wav",
// "sounds/hokkanen/ööö.wav"
// ]);

// Salkkarit.Models.soundPathCollections.push([
// "sounds/ismo4/(ismo tulee oven läpi).wav",
// "sounds/ismo4/ah öö terve.wav",
// "sounds/ismo4/avaa ovi kuulitko!.wav",
// "sounds/ismo4/avaa ovi!.wav",
// "sounds/ismo4/ei sun tartte mulle rautalangasta vääntää, työkavereiden on hyvä pysyä vaa työkavereina.wav",
// "sounds/ismo4/ei tää kyl yhtä hyvää oo ku sun tekemä.wav",
// "sounds/ismo4/eikä semmonen maksaiskaa varmaa paljon.wav",
// "sounds/ismo4/eilen illalla.wav",
// "sounds/ismo4/en aio.wav",
// "sounds/ismo4/enkä mä viittiny soitella niiden peräään ja pilaamaan niiden matkaa kun eihän tälle nyt enään mitään voi.wav",
// "sounds/ismo4/haudanhoitomaksu.wav",
// "sounds/ismo4/hei tyttö mitä sä laitoit sinne takin alle nyt sä pysyt siinä.wav",
// "sounds/ismo4/helvetin sen lempikeksejä.wav",
// "sounds/ismo4/hemmetin roope ankka.wav",
// "sounds/ismo4/huumeita meidän kellarissa.wav",
// "sounds/ismo4/huumeita.wav",
// "sounds/ismo4/ihan toimiva kahvinkeitin se on. se on viimevuoden mallia.wav",
// "sounds/ismo4/ihmislihaaaa.wav",
// "sounds/ismo4/imuroija.wav",
// "sounds/ismo4/ismo laitela.wav",
// "sounds/ismo4/ismo ähisee.wav",
// "sounds/ismo4/ismon kiulu kolahtaa.wav",
// "sounds/ismo4/ja nyt sinä pidät turpas kiinni.wav",
// "sounds/ismo4/ja ties mitämuuta.wav",
// "sounds/ismo4/jaa että televisoko no tottakai se toimii.wav",
// "sounds/ismo4/jaa pojat kävi saunas vai.wav",
// "sounds/ismo4/jenni ja ossi.wav",
// "sounds/ismo4/joo kaikki arvokas oli viety.wav",
// "sounds/ismo4/joo.wav",
// "sounds/ismo4/kaikki arvokas on viety.wav",
// "sounds/ismo4/kaksisataa.wav",
// "sounds/ismo4/kassan alle piiloon.wav",
// "sounds/ismo4/kato nyt totaki ihme etteivät lamborghinia ostaneet.wav",
// "sounds/ismo4/kiitoksia ja tervetuloa uudestaan.wav",
// "sounds/ismo4/ku mä olin elokuvissa.wav",
// "sounds/ismo4/ku vanhan kotteron voi jättää viikkokausiks ovet auki eikä kukaan koske.wav",
// "sounds/ismo4/kuule hei sovitaanko että mä soitan sulle kohta uudestaan.wav",
// "sounds/ismo4/kuule tää mun seuralainen on kauniimpi ku yksikään missi.wav",
// "sounds/ismo4/kuulkaa mulle tulee nyt toinen puhelu. soittakaa mulle jos muutatte mielenne kiitos kuulemiin.wav",
// "sounds/ismo4/kyllä mä sen ymmärrän.wav",
// "sounds/ismo4/kyllä uskomaton juttu keskellä iltaa.wav",
// "sounds/ismo4/kymmenen euroo on mun viimenen tarjous, ottakaa tai jättäkää.wav",
// "sounds/ismo4/laittamaan.wav",
// "sounds/ismo4/lukkoseppä sarjottaa uutta lukkoa tuolla sisällä.wav",
// "sounds/ismo4/lyödä sua.wav",
// "sounds/ismo4/matontamppaaja.wav",
// "sounds/ismo4/meidän kellarissa.wav",
// "sounds/ismo4/melko kiree.wav",
// "sounds/ismo4/mik.wav",
// "sounds/ismo4/mikäettei.wav",
// "sounds/ismo4/missi.wav",
// "sounds/ismo4/mun nimi on ismo laitela.wav",
// "sounds/ismo4/mä annoin jo.wav",
// "sounds/ismo4/mä en huomannukkaa teitä.wav",
// "sounds/ismo4/mä en oo ihan varma onko se siellä vessassa.wav",
// "sounds/ismo4/mä en viittiny laittaa tarkempaa osotetta nettiin.wav",
// "sounds/ismo4/mä haluaisin.wav",
// "sounds/ismo4/mä haluisin puhua siitä suudelmasta.wav",
// "sounds/ismo4/mä juttelin sen naisen kanssa.wav",
// "sounds/ismo4/mä nyt oon vaan tämmönen tavallinen pulliainen enkä mikää unelmien prinssi.wav",
// "sounds/ismo4/mä oon kuule ihan kykenevä jatkamaan siitä mihin me jäätiin.wav",
// "sounds/ismo4/mä oon sen ikänen mies etten enää rupea hameväen perään huutelemaan.wav",
// "sounds/ismo4/mä tuon kahvit.wav",
// "sounds/ismo4/mä vaan en satu olemaan sun tyyppiäs ei sitä tarvi sen enemmän selitellä.wav",
// "sounds/ismo4/mörrrköjä.wav",
// "sounds/ismo4/naiset ensin.wav",
// "sounds/ismo4/ne on risteilyllä.wav",
// "sounds/ismo4/ne on varmaan tulossa tänne.wav",
// "sounds/ismo4/nii ja kuntoilemassa kuten muistatte.wav",
// "sounds/ismo4/no eihän se nyt sun vikas ollu se tyttöhän sua tönäs.wav",
// "sounds/ismo4/no joka tapaukses tuu va pyytää apua jos sitä kaipaat.wav",
// "sounds/ismo4/no kävi ilmi että sitä hävettää olla mun seurassa.wav",
// "sounds/ismo4/no se taas ei kuulu sulle.wav",
// "sounds/ismo4/ohhohho.wav",
// "sounds/ismo4/ottaaks joku verta.wav",
// "sounds/ismo4/ottasitsä pullaa.wav",
// "sounds/ismo4/panitkos muuten sinä autos lukkoon.wav",
// "sounds/ismo4/pannu.wav",
// "sounds/ismo4/perää.wav",
// "sounds/ismo4/pitäisköhän meidän pyytää ne tähän samaan pöytään.wav",
// "sounds/ismo4/pitää varmaa rupee pitää tota ulko-ovea lukossa.wav",
// "sounds/ismo4/rappuunhan ois voinu tulla kukatahansa.wav",
// "sounds/ismo4/ruosteessa mä oon ja pahasti.wav",
// "sounds/ismo4/salla.wav",
// "sounds/ismo4/se oli myymälävaras.wav",
// "sounds/ismo4/se on vessassa.wav",
// "sounds/ismo4/seisoa.wav",
// "sounds/ismo4/seisoo.wav",
// "sounds/ismo4/seppo ja ulla.wav",
// "sounds/ismo4/sua siis hävettäis myöntää että oot treffeillä mun kanssa.wav",
// "sounds/ismo4/sua.wav",
// "sounds/ismo4/suihkussa.wav",
// "sounds/ismo4/sun.wav",
// "sounds/ismo4/suolii.wav",
// "sounds/ismo4/sä voit tulla sieltä jo ylös.wav",
// "sounds/ismo4/säästyy monelta sotkulta.wav",
// "sounds/ismo4/taulut.wav",
// "sounds/ismo4/televisio videot korurasiat taulut.wav",
// "sounds/ismo4/televisio.wav",
// "sounds/ismo4/televisiostako sä nyt oot kiinnostunut vai siitä taidetaulusta.wav",
// "sounds/ismo4/terve ja heipä hei mä olen niksi-ismo ja tänään mä näytän teille kuinka.wav",
// "sounds/ismo4/tervetuloa tervetuloa.wav",
// "sounds/ismo4/toihan kuulostaa hienolta.wav",
// "sounds/ismo4/tti.wav",
// "sounds/ismo4/tunnet sä sen.wav",
// "sounds/ismo4/tuolla ulkona.wav",
// "sounds/ismo4/tyyne puustisen haaaaaamu.wav",
// "sounds/ismo4/tässä mulla on ihan tavallinen ämpäri jossa on kymmenen litraa vettä.wav",
// "sounds/ismo4/täähän on vasta alkulämmittelyä.wav",
// "sounds/ismo4/täällä on nyt käyny sillä tavalla että tänne on murtauduttu.wav",
// "sounds/ismo4/ufff uufff ahhh.wav",
// "sounds/ismo4/ullan korurasia.wav",
// "sounds/ismo4/unelmien prinssi.wav",
// "sounds/ismo4/vaikka sehän noissa uusissa autoissa on että ne kiinnostaa varkaitakin enemmän.wav",
// "sounds/ismo4/verta.wav",
// "sounds/ismo4/video.wav",
// "sounds/ismo4/visa.wav",
// "sounds/ismo4/voihan sitä joskus käydä niinki.wav",
// "sounds/ismo4/yleensä ihmiset suutelee jostai tietystä syystä.wav",
// "sounds/ismo4/ähh toi maito unohtu.wav",
// "sounds/ismo4/öööö itseasiassa.wav"
// ]);

// Salkkarit.Models.soundPathCollections.push([
// "sounds/kari/annahan mennä.wav",
// "sounds/kari/Ei helvetti.wav",
// "sounds/kari/ei se oona suostunut.wav",
// "sounds/kari/Et voi ikinä uskoa mitä se tyttö on menny tekemään.wav",
// "sounds/kari/halookuuleekokukaan.wav",
// "sounds/kari/haluutsäkuonoos.wav",
// "sounds/kari/idiootti.wav",
// "sounds/kari/ihan sama mitä mä oon tehny, te ootte miron kans alaikäsiä.wav",
// "sounds/kari/ja mitähän se seurustelu sulle oikei merkitsee.wav",
// "sounds/kari/jossävielhiiviskelet.wav",
// "sounds/kari/Kari - Ai rupeet sä faijaas neuvomaan.wav",
// "sounds/kari/Kari - Ala nyt puhumaan tai saat ettii jonkun muun sohvan asuinpaikakseks.wav",
// "sounds/kari/Kari - Annas tulla totuus.wav",
// "sounds/kari/Kari - Eikä siinä kaikki.wav",
// "sounds/kari/Kari - Eli tää on niin sanottu vahinko.wav",
// "sounds/kari/Kari - Ismo oli vieny sut kaks kertaa lääkäriin.wav",
// "sounds/kari/Kari - Joku ilmoitti et siel on huumeita.wav",
// "sounds/kari/Kari - Kuulin äsken aika hurjia uutisia.wav",
// "sounds/kari/Kari - Kuulostaa aika säälittävältä.wav",
// "sounds/kari/Kari - Kyllä olen juonut.wav",
// "sounds/kari/Kari - Meikäläinen laitto pentuna aina kuumemittarin kuumaan veteen et sai jäädä himaan.wav",
// "sounds/kari/Kari - Minkä takia se lääkäriä pelkäs.wav",
// "sounds/kari/Kari - Miten musta tuntuu että sä salaat multa jotakin.wav",
// "sounds/kari/Kari - Miten tää on ylipäätään mahdollista.wav",
// "sounds/kari/Kari - Mulla ainakin on pelkkiä iloja ku ei tullu kuulaa kalloon.wav",
// "sounds/kari/Kari - Mun ja Nooran ero ei liity millään tavalla Nooran sairauteen.wav",
// "sounds/kari/Kari - Mun piti kerätä lisää todisteita.wav",
// "sounds/kari/Kari - Mä oon voinu saada tartunnan.wav",
// "sounds/kari/Kari - Mä yritän saada tän naisen puhumaan.wav",
// "sounds/kari/Kari - No aattelin vaan ku sä olit kuulemma kuskannu sen lääkäriinki.wav",
// "sounds/kari/Kari - No en oo paljoo haalareita tässä kerinny miettimään.wav",
// "sounds/kari/Kari - No mikä meininki.wav",
// "sounds/kari/Kari - No minkäs takia siellä kaks kertaa piti käydä.wav",
// "sounds/kari/Kari - No mut mehän ollaan oltu tositarkkoja ehkäsyn kanssa.wav",
// "sounds/kari/Kari - No mä oon kuule niin kova jätkä että muhun ei sun pöpöt tartu.wav",
// "sounds/kari/Kari - No turhaa tarkistat et sä kuitenkaan mitään voita.wav",
// "sounds/kari/Kari - Onks tässä sun puljussa mustaherukkamehua.wav",
// "sounds/kari/Kari - Pidä sinä huoli vaan omasta hygieniastas.wav",
// "sounds/kari/Kari - SANO NYT MIKÄ HELVETTI SULLA OIKEIN ON.wav",
// "sounds/kari/Kari - Sano vaan jos mä voin tehdä jotain.wav",
// "sounds/kari/Kari - Sege Kuulanen, se oli uhkaillu poikia aseella.wav",
// "sounds/kari/Kari - Tossa se HIV pariskunta nyt menee.wav",
// "sounds/kari/Kari - Tää on mahtava juttu, musta tulee taas isukki.wav",
// "sounds/kari/Kari - Tää on täyttä totta.wav",
// "sounds/kari/Kari - Älä pelleile.wav",
// "sounds/kari/karivsjoona.wav",
// "sounds/kari/keltä sä ton oikei sait.wav",
// "sounds/kari/Kuule ooppa onnellinen ettei palanu koko sauna tai talo.wav",
// "sounds/kari/kyllä mä teinikundit tiiän.wav",
// "sounds/kari/kyllä se sieltä tulee.wav",
// "sounds/kari/Kyllähän mä heti arvasin että laiska tunarihan sä vaan oot.wav",
// "sounds/kari/Meet omaan huoneesees ja mietit vähän mitä oot tehny.wav",
// "sounds/kari/Miten sä sait sen kiukaan tuhottuu.wav",
// "sounds/kari/mitenniiei.wav",
// "sounds/kari/mitäs sä oikei haluut mun tyttärestä.wav",
// "sounds/kari/mä haluan vaa mun tyttäreni parasta, miehet on sikoja.wav",
// "sounds/kari/mä olen kari taalasmaa.wav",
// "sounds/kari/Niin muuten vaan vetäsit kännit ja panit paikat remonttiin.wav",
// "sounds/kari/no en ennenku kerrot ketä varten sä niitä kortsuja ostelet.wav",
// "sounds/kari/no justhan se imi sun kaulas mustaks.wav",
// "sounds/kari/no tällä kertaa mä en oo syyllinen.wav",
// "sounds/kari/nonii.wav",
// "sounds/kari/näin just miron kaulassa fritsun ja sul on taatusti samanlainen.wav",
// "sounds/kari/olutta.wav",
// "sounds/kari/onks sul olutta.wav",
// "sounds/kari/perkule.wav",
// "sounds/kari/pidäs poika pääs kiinni ja kuuntele.wav",
// "sounds/kari/Pistä se puukko nyt pois.wav",
// "sounds/kari/pitäskö puhua sen helenan kanssa.wav",
// "sounds/kari/se nyt kapinoi kaikkee vastaan mitä sä ehdotat.wav",
// "sounds/kari/Sepin ja Karin kännilaulu.wav",
// "sounds/kari/sillä nyt on sellanen vaihe.wav",
// "sounds/kari/sinne se lukittautu.wav",
// "sounds/kari/sä et lähe mihinkään.wav",
// "sounds/kari/sä saat mun pinnan katkeemaan harvinaisen helposti.wav",
// "sounds/kari/tajuatko sä että imuttelusta.wav",
// "sounds/kari/tuomotervajoki.wav",
// "sounds/kari/turpaanvetäjäisiin.wav",
// "sounds/kari/Typerät kakarat mitä te ootte menny tekemään.wav",
// "sounds/kari/viis donaa.wav",
// "sounds/kari/Voi helvetti se karkas kun mä nukuin.wav",
// "sounds/kari/älä jauha paskaa.wav"
// ]);

// Salkkarit.Models.soundPathCollections.push([
// "sounds/lasse/asiathoidetaaan.wav",
// "sounds/lasse/Ei Ei Ei Ei Paula Ei Ei EI.wav",
// "sounds/lasse/Eihän se nyt mikään kani oo.wav",
// "sounds/lasse/Ekaks katoo muija ja sitten katoo ruuvarit ja nyt.wav",
// "sounds/lasse/Hyvää yötä.wav",
// "sounds/lasse/Ihanat juhlat hähää.wav",
// "sounds/lasse/jokaasiasta vääntää.wav",
// "sounds/lasse/jos mä en nää mun autoa sinä mihi mä sen jätin.wav",
// "sounds/lasse/jumaliste.wav",
// "sounds/lasse/Kelle sä oikein naputat.wav",
// "sounds/lasse/Ketä nää tyypit o.wav",
// "sounds/lasse/Kysyppäs Paulatädiltä että minkätakia Lassesetä ylipäätänsä on talonmies.wav",
// "sounds/lasse/Lasse - Ja sä oot niin hirveen herkkä.wav",
// "sounds/lasse/lasse auto.wav",
// "sounds/lasse/lasse puhelin auto.wav",
// "sounds/lasse/lasse puhelin nyt tehäänki rikosilmotus.wav",
// "sounds/lasse/lasse puhelin varas!.wav",
// "sounds/lasse/lasse puhelin voi perhana.wav",
// "sounds/lasse/Lasse Sievi.wav",
// "sounds/lasse/mansikat.wav",
// "sounds/lasse/Mistä sä tiedät kuka siinä perheessä on hirviö.wav",
// "sounds/lasse/miten niii varma.wav",
// "sounds/lasse/Mitä, loppuks se jo.wav",
// "sounds/lasse/muna uto on kadonnu.wav",
// "sounds/lasse/munauto.wav",
// "sounds/lasse/mävoinauttaasua.wav",
// "sounds/lasse/naapurii.wav",
// "sounds/lasse/niks naks henki pois.wav",
// "sounds/lasse/Niks naks, henki pois.wav",
// "sounds/lasse/No aina jää kaikki parhaat palat näkemättä.wav",
// "sounds/lasse/No missä hemmetissä avaimet on.wav",
// "sounds/lasse/onnellinenperkele.wav",
// "sounds/lasse/Paula hei jos mihelle annetaan kivääri niin se ottaa mielummin kiväärin kuin voileivän.wav",
// "sounds/lasse/Perhana.wav",
// "sounds/lasse/perkele teette sen työnne ja hommaatte mun vaimon takas.wav",
// "sounds/lasse/perrrhana.wav",
// "sounds/lasse/roskalava.wav",
// "sounds/lasse/rrrhana mä vedän siltä jätkältä niskat nurin.wav",
// "sounds/lasse/Se on turvakodissa.wav",
// "sounds/lasse/Sä otat nyt sen askeleen taaksepäin.wav",
// "sounds/lasse/Sä painut ulos ja sä otat sun kamas mun ja Paulan asunnosta.wav",
// "sounds/lasse/tappo ittensä.wav",
// "sounds/lasse/tarviitsäapua.wav",
// "sounds/lasse/turvakodissa.wav",
// "sounds/lasse/varas.wav",
// "sounds/lasse/Viimeks ku mä olin Paulan kanssa oopperassa ni meinas tulla porttikielto.wav",
// "sounds/lasse/Älä nyt jaksa viitsiä.wav"
// ]);

// Salkkarit.Models.soundPathCollections.push([
// "sounds/maarit/AHHHH.wma",
// "sounds/maarit/anna tulla vaa kaikki.wav",
// "sounds/maarit/annappa tulla vaa.wav",
// "sounds/maarit/Anteekspyyntö.wma",
// "sounds/maarit/ei oo totta.wav",
// "sounds/maarit/Ei1.wma",
// "sounds/maarit/Ei2.wma",
// "sounds/maarit/Eiko sua  yhtää hävetä.wma",
// "sounds/maarit/Eikä Syyttä.wma",
// "sounds/maarit/Hei mä ihan oikeesti haluisin jutella sun kannsas sun kokemuksis.wma",
// "sounds/maarit/hei nyt nyt nyt nyt.wav",
// "sounds/maarit/Hei Pistä Se Samantien Tuplana.wma",
// "sounds/maarit/Hei Taas.wma",
// "sounds/maarit/Hei2.wma",
// "sounds/maarit/Hyva.wma",
// "sounds/maarit/HYVÄ.wma",
// "sounds/maarit/ismolta.wav",
// "sounds/maarit/Ja nimettomana jos sa haluat.wma",
// "sounds/maarit/johansopankeitin.wav",
// "sounds/maarit/Jutella.wma",
// "sounds/maarit/Kai mä nyt tajuan että te tapailette salaa.wav",
// "sounds/maarit/Kato siita ei muuten lahde makua.wma",
// "sounds/maarit/Kertoo.wma",
// "sounds/maarit/Kohtelemaan Tanjaa Kunnolla.wma",
// "sounds/maarit/Kunnolla.wma",
// "sounds/maarit/Kylläseny pysty töihin lähtemää mutta erittäin surkeella mielell.wma",
// "sounds/maarit/kylläseonvarastamista.wav",
// "sounds/maarit/laitasnytmunpää.wav",
// "sounds/maarit/Maarit vs Sofia.wav",
// "sounds/maarit/Mahdollisuuden.wma",
// "sounds/maarit/Makua.wma",
// "sounds/maarit/Mietis nyt tarkkaa.wma",
// "sounds/maarit/Mietis.wma",
// "sounds/maarit/Minä minä minä minä.wma",
// "sounds/maarit/minä olen maksava asiakas.wav",
// "sounds/maarit/Missä Se sitruuna nyt on.wma",
// "sounds/maarit/Mitä ihmettä.wav",
// "sounds/maarit/mitä sä teet.wav",
// "sounds/maarit/Mitäh.wav",
// "sounds/maarit/Mstäköhän.wma",
// "sounds/maarit/Mun luo koska se ei uskaltanu jäädä kotiinsa.wma",
// "sounds/maarit/mä laitan sängyn.wav",
// "sounds/maarit/Mä tein ittestäni täys pellen.wav",
// "sounds/maarit/No kylläpä oli hyvä että tulit järkiis ja jäit tänne.wav",
// "sounds/maarit/No mut sehän on hieno saavutus.wav",
// "sounds/maarit/No Seppo ja Tanja luuli että se oli varastanu kaupasta.wav",
// "sounds/maarit/Oma.wma",
// "sounds/maarit/Paha Ihminen.wma",
// "sounds/maarit/Perille.wma",
// "sounds/maarit/poliisille.wav",
// "sounds/maarit/puhtaaltapöydältä.wav",
// "sounds/maarit/rakastuneelta.wav",
// "sounds/maarit/Rakkaus niin olen niin olen.wma",
// "sounds/maarit/Riitä.wma",
// "sounds/maarit/Ruvennu Ryyppäämään.wma",
// "sounds/maarit/ryyppäämään.wav",
// "sounds/maarit/saako tulla.wav",
// "sounds/maarit/Se on Ihanaa.wma",
// "sounds/maarit/Se on siis totta.wav",
// "sounds/maarit/Se struuna pitää laittaa sinne ensimmäiseks eikä viimeseks.wma",
// "sounds/maarit/Sen Takia.wma",
// "sounds/maarit/Sitruuna.wma",
// "sounds/maarit/Sun On Ihan Pakko Ruveta.wma",
// "sounds/maarit/Tai mulle tai Aleksille.wav",
// "sounds/maarit/Tanja.wma",
// "sounds/maarit/Tarkkaa.wma",
// "sounds/maarit/Toinen Samanlainen.wma",
// "sounds/maarit/Tuli turvaa.wma",
// "sounds/maarit/Tuo Chili.wma",
// "sounds/maarit/tääonhuonoidea.wav",
// "sounds/maarit/Töihin.wma",
// "sounds/maarit/Versio.wma",
// "sounds/maarit/Voi Lasse elamani Suurin Rakkaus.wma"
// ]);

// Salkkarit.Models.soundPathCollections.push([
// "sounds/miro/Emmä oikein tiedä, mitähän sun faija siitä tykkäis.mp3",
// "sounds/miro/faija.wav",
// "sounds/miro/Haluutsä jotain ylläri lapsii tai et mä saan jonkun sukupuoli taudin.mp3",
// "sounds/miro/Hohhoijjaa.mp3",
// "sounds/miro/Kannattas muuten mennä johonki suojaan.wav",
// "sounds/miro/Kyllähän mä nuo kaikki tiedän.mp3",
// "sounds/miro/maikka vahtii omas rapus.wav",
// "sounds/miro/merilevää.wav",
// "sounds/miro/Mut sä et halua, et mä nimenomaan käytän niitä oon kanssa.mp3",
// "sounds/miro/mutsi.wav",
// "sounds/miro/mä ja faija vastaan te muut.wav",
// "sounds/miro/Niin, sä kutsuit mut vaan sen takia tänne, et sä et uskalla kattoo tätä ittekses.mp3",
// "sounds/miro/Omat kortsus.mp3",
// "sounds/miro/panin.wav",
// "sounds/miro/paska.wav",
// "sounds/miro/peikkotyttö.wav",
// "sounds/miro/Pidätsä mua jonain viis vuotiaana tai idioottina.mp3",
// "sounds/miro/supersankari viemäs neidol kanakeittoo.wav",
// "sounds/miro/Tiedoks vaan, ei Oona oo mun eka tyttöystävä.mp3",
// "sounds/miro/turpaa.wav"
// ]);

// Salkkarit.Models.soundPathCollections.push([
// "sounds/Miron pissikset/Hei Zori.wav",                           "Kuulizä meidän luokal on julkkis.wav",
// "sounds/Miron pissikset/Me haluttais kysyy sult jotain.wav",     "Mä oon Lissu ja täs on Heidi.wav",
// "sounds/Miron pissikset/Onx Jacques Jardin sun isäh.wav",        "Oot sä toi kundi tossa.wav",
// "sounds/Miron pissikset/Toi sun kuva on aika söpö.wav",          "Tää tuli meikkien mukana.wav"
// ]);

// Salkkarit.Models.soundPathCollections.push([
// "sounds/niko/eioonälkä.wav",                       "emmätiiä.wav",
// "sounds/niko/jauhopeukalo.wav",                    "kauheenipo.wma",
// "sounds/niko/kiitti.wma",                          "mitenniin.wma",
// "sounds/niko/mitääääh.wma",                        "mutmäenvaantiedä.wma",
// "sounds/niko/no en mätajunnu.wma",                 "noenyhtäänhmettele.wma",
// "sounds/niko/okei.wma",                            "pipareita.wav",
// "sounds/niko/päästäirti.wma",                      "sehäntyrmäämut.wma",
// "sounds/niko/söootitekkinihanpinnanasiihen.wma"
// ]);

// Salkkarit.Models.soundPathCollections.push([
// "sounds/noora/ei sun tartte selittää.wav",
// "sounds/noora/Ei voi olla totta.wav",
// "sounds/noora/haluutsä nähä mun valokuvat.wav",
// "sounds/noora/Hitto mikä sika se on.wav",
// "sounds/noora/Ja silti sä kehtaat kiukutella Tanjalle ku mikäki pikkukakara.wav",
// "sounds/noora/Jos sussa on yhtään miestä.wav",
// "sounds/noora/kasku et lähe röökille.wav",
// "sounds/noora/kyllä mä kestän kriisit.wav",
// "sounds/noora/Lopeta toi typerä pelleily ja mieti edes hetken käytöstäs.wav",
// "sounds/noora/mul on hiv.wav",
// "sounds/noora/mun kanssa.wav",
// "sounds/noora/Mä en kattois tollasta sekuntiakaan.wav",
// "sounds/noora/Mä en kyllä ymmärrä miten se Tanja ylipäätään sietää sua.wav",
// "sounds/noora/mä pakotin.wav",
// "sounds/noora/mä sanoin karille.wav",
// "sounds/noora/mäki haluun sua.wav",
// "sounds/noora/no yrittäisit.wav",
// "sounds/noora/Noora - HIV ei kuule lähe pelkällä mustaherukkamehulla.wav",
// "sounds/noora/Noora - HIV voi olla kellä tahansa.wav",
// "sounds/noora/Noora - Jos et sä nyt kohta lähe ni mä alan taas pillittää.wav",
// "sounds/noora/Noora - Juu kiitos en tarvitse apua, varsinkaan mieheltä joka on pahoinpidellyt mun siskoo.wav",
// "sounds/noora/Noora - Kieltämättä jännittää kertoa koko maailmalle olevansa HIV positiivinen.wav",
// "sounds/noora/Noora - Kiitos.wav",
// "sounds/noora/Noora - Mikään ehkäsy ei oo 100 prosenttisen varma.wav",
// "sounds/noora/Noora - Mitä jos mul on AIDS.wav",
// "sounds/noora/Noora - Mul tuli humahdus.wav",
// "sounds/noora/Noora - Mun sairaus on edennyt seuraavan vaiheeseen, mul on AIDS.wav",
// "sounds/noora/Noora - Mä en ookkaan ikinä maistanu tätä rouhenjuusteetä.wav",
// "sounds/noora/Noora - Mä oon raskaana.wav",
// "sounds/noora/Noora - No ei muuta ku kimppuun vaan.wav",
// "sounds/noora/Noora - No miten lapsia yleensä tehdään.wav",
// "sounds/noora/Noora - No siihen on lääkkeitä ja suurin osa HIV potilaiden lapsista syntyy terveinä.wav",
// "sounds/noora/Noora - Pliis Ismo tää on mule tosi tärkeetä.wav",
// "sounds/noora/Noora - Sil on yks tärkee juttu.wav",
// "sounds/noora/Noora - Tosi hauskaa.wav",
// "sounds/noora/Noora - Tulikohan näihin nyt vähän liikaa valkosipulia.wav",
// "sounds/noora/O-ou, sä haluut varmaan häämatkalle Norjaan.wav",
// "sounds/noora/oisit itekki jos oisit minä.wav",
// "sounds/noora/onks suunnitelmia.wav",
// "sounds/noora/otanloparit.wav",
// "sounds/noora/panna.wav",
// "sounds/noora/pitäiskö keittää kahvii.wav",
// "sounds/noora/Pysähdy mä oon sun pomo mä keskin sua pysähtyä.wav",
// "sounds/noora/rakastan.wav",
// "sounds/noora/Seki on tehny sun eteen vaikka mitä.wav",
// "sounds/noora/suojaamatonta seksiä.wav",
// "sounds/noora/sä haluut lopettaa tä.wav",
// "sounds/noora/Sä oot tehny virheen, sä oot lyöny.wav",
// "sounds/noora/sänkyyn.wav",
// "sounds/noora/tuliks ikävä.wav",
// "sounds/noora/turha sun on pelätä.wav",
// "sounds/noora/tuu tänne nii saat kahvia.wav",
// "sounds/noora/tuutsä meille.wav",
// "sounds/noora/voisit lopettaa.wav",
// "sounds/noora/äkkiä nyt.wav",
// "sounds/noora/älä lähe mihinkää.wav"]);

// Salkkarit.Models.soundPathCollections.push([
// "sounds/oona/Ei ku mä ja Joulupukki.wav",
// "sounds/oona/huomenta kulta.wav",
// "sounds/oona/jauhelihapullia ja muusia.wav",
// "sounds/oona/Jätä mut rauhaan.wav",
// "sounds/oona/me mentii miron kans kihloihi.wav",
// "sounds/oona/Mitä hemmettiä sä oikein meinaat.wav",
// "sounds/oona/Mä oon Miron mielestä vastenmielinen mangapeikko.wav",
// "sounds/oona/ne on sushia.wav",
// "sounds/oona/No en usko ja sehän on vaan terveellistä.wav",
// "sounds/oona/no mitä siel kellaris tapahtu.wav",
// "sounds/oona/Oot sä seonnut.wav",
// "sounds/oona/panoseuraa.wav",
// "sounds/oona/raakaa tonnikalaa ja mätiä.wav",
// "sounds/oona/Sä oot välillä niin idiootti.wav"]);

// Salkkarit.Models.soundPathCollections.push([
// "sounds/paula/Ihanaa.wav",
// "sounds/paula/Ja sekö oikeuttaa sua hakkaamaan läheisiäs.wav",
// "sounds/paula/karkaa.wav",
// "sounds/paula/lassen auto on varastettu.wav",
// "sounds/paula/me etittii koko kortteli ympäri ei missää.wav",
// "sounds/paula/Millä oikeudella te siinä nauratte.wav",
// "sounds/paula/Mitä tapahtu.wav",
// "sounds/paula/Niin mut jos sul tulee täällä kylmä.wav",
// "sounds/paula/Olisitko sä voinut tappaa Lauran.wav",
// "sounds/paula/Paula - Et oo tosissas.wav",
// "sounds/paula/Paula - HÖPSIS!.wav",
// "sounds/paula/Paula - Lähestymiskielto.wav",
// "sounds/paula/Paula - Mitä sä täällä teet.wav",
// "sounds/paula/Paula - No voihan sen vuokrata DVDnä.wav",
// "sounds/paula/Paula - Paula Sievinen.wav",
// "sounds/paula/Paula - Sun takias mä en vastannu.wav",
// "sounds/paula/Paula - Sä kielsit mua vastaamasta Tuulin puheluun.wav",
// "sounds/paula/Paula - Tuuli on tehny itsemurhan.wav",
// "sounds/paula/Paula - Tuulille.wav",
// "sounds/paula/Puhuitko sä edes Sepolle että sä et ole työkykyinen.wav",
// "sounds/paula/Sä näytätki voivan paremmin.wav",
// "sounds/paula/Tajuatko sä Ismo miten alas sä oot vajonnut.wav",
// "sounds/paula/Tanja teki ihan oikein ku jätti sut.wav"]);

// Salkkarit.Models.soundPathCollections.push([
// "sounds/Resisposse/joku kirjottaa sanoja.wav",     "kallen laulu.wav",
// "sounds/Resisposse/kallen muija.wav",              "mm-m.wav",
// "sounds/Resisposse/mullon oma bändiki.wav",        "no joo kyllä olen olen.wav",
// "sounds/Resisposse/no on on aika paljonkin.wav",   "noolen.wav",
// "sounds/Resisposse/olenhan minä kuule.wav",        "olenhan minä.wav",
// "sounds/Resisposse/olenolen.wav",                  "resisposse.wav",
// "sounds/Resisposse/tää on kwan bändistä.wav",      "tää on tää on.wav",
// "sounds/Resisposse/öö.wav"]);

// Salkkarit.Models.soundPathCollections.push([
// "sounds/romeo/ainaki yks tyyppi tietää totuuden.wav",
// "sounds/romeo/ehtisit sä käydä viel kahvilla ennenku.wav",
// "sounds/romeo/ei oo mun ongelma.wav",
// "sounds/romeo/eikä mitää muuta.wav",
// "sounds/romeo/eli tilanne on paranemaan päin.wav",
// "sounds/romeo/emmä sua pelkää.wav",
// "sounds/romeo/haluut sä et mä jään tänne kuulustelemaa.wav",
// "sounds/romeo/huomenta.wav",
// "sounds/romeo/hyvä.wav",
// "sounds/romeo/iha hienoo.wav",
// "sounds/romeo/jätkä feikkaa, teil on selvästi jotai sutinaa.wav",
// "sounds/romeo/kenel on bileet.wav",
// "sounds/romeo/kiitti.wav",
// "sounds/romeo/kiva ku sain kuunnella.wav",
// "sounds/romeo/kyl sä oisit sen iteki keksiny.wav",
// "sounds/romeo/lähe vetää tai mä soitan poliisille.wav",
// "sounds/romeo/Maarit aikoo lukita sut johonkin torniin.wav",
// "sounds/romeo/missä.wav",
// "sounds/romeo/mitennii.wav",
// "sounds/romeo/mitä sä haluut.wav",
// "sounds/romeo/mitä sä siin teet.wav",
// "sounds/romeo/mo eikä ole.wav",
// "sounds/romeo/must ois korkee aika sulle laputtaa kotii.wav",
// "sounds/romeo/must teet pahan virheen jos lähet nyt.wav",
// "sounds/romeo/mä en saanu siit mitää maksuu.wav",
// "sounds/romeo/mä oon tosi tyytyväinen sun puolesta.wav",
// "sounds/romeo/mä rakastan sitä ja se mua.wav",
// "sounds/romeo/mäkää en oo nähny sofiaa.wav",
// "sounds/romeo/noh jännittääkö.wav",
// "sounds/romeo/oon pahoillani niist kerroist ku.wav",
// "sounds/romeo/oot sä rakastunu.wav",
// "sounds/romeo/oot sä varma et noin voi tehä no jalat pöydäl.wav",
// "sounds/romeo/se o vanha viisaus.wav",
// "sounds/romeo/Sä et ampunut ketään, se ase vahingos laukes.wav",
// "sounds/romeo/sä oot varmaa sofian faija.wav",
// "sounds/romeo/tultii ostaa maijalle näkkärii.wav",
// "sounds/romeo/uskot sä oikeesti et tanjuska on sun äiti.wav",
// "sounds/romeo/vaik kaikki yrittää parhaansa nii joku mogaa.wav"]);

// Salkkarit.Models.soundPathCollections.push([
// "sounds/salla/eisaatöniä.wav",             "enkäjaksaodottaa.wav",
// "sounds/salla/etkösäälyäkosia.wav",        "hyvinhänsemeni.wav",
// "sounds/salla/idiootti.wav",               "jamistäsentiedät.wav",
// "sounds/salla/lapsia.wav",                 "miks.wav",
// "sounds/salla/mitämäteen.wav",             "mäenkestä.wav",
// "sounds/salla/mähaluannaimisiin.wav",      "mäoonainahalunnu.wav",
// "sounds/salla/niinkökulta.wav",            "nytkösetapahtuu.wav",
// "sounds/salla/painatvaanhuiskimaan.wav",   "vau.wav"]);

// Salkkarit.Models.soundPathCollections.push([
// "sounds/Sepon eduskuntakaveri/aivan.wav",                               "akraarit.wav",
// "sounds/Sepon eduskuntakaveri/iltaa.wav",                               "jamissäse.wav",
// "sounds/Sepon eduskuntakaveri/kansanmies.wav",                          "kyseeiookkaantoistenasioistavaan.wav",
// "sounds/Sepon eduskuntakaveri/leipä.wav",                               "leipää.wav",
// "sounds/Sepon eduskuntakaveri/maaseudulla.wav",                         "maaseudun.wav",
// "sounds/Sepon eduskuntakaveri/me suomen.wav",                           "meidänkaikkien.wav",
// "sounds/Sepon eduskuntakaveri/mutetkösinäkisyö.wav",                    "mätiesinseppoettähoksottimetpelaa.wav",
// "sounds/Sepon eduskuntakaveri/nomistäse.wav",                           "on.wav",
// "sounds/Sepon eduskuntakaveri/pellosta.wav",                            "pidäunohtaa.wav",
// "sounds/Sepon eduskuntakaveri/pienenkin ihmisen.wav",                   "pienistäkasvaaisoja.wav",
// "sounds/Sepon eduskuntakaveri/pitäätullaesiin.wav",                     "rouva.wav",
// "sounds/Sepon eduskuntakaveri/säoletpohjimmiltas.wav",                  "tulee.wav",
// "sounds/Sepon eduskuntakaveri/väkeä.wav"]);

// Salkkarit.Models.soundPathCollections.push([
// "sounds/seppo/ajattelinkokeillavoiskotällä.wav",
// "sounds/seppo/alaikäselle.wav",
// "sounds/seppo/demonikähveltäjä.wav",
// "sounds/seppo/eeeieeei - puhelin.wav",
// "sounds/seppo/eeeieeei.wav",
// "sounds/seppo/ehkäpä - puhelin.wav",
// "sounds/seppo/ehkäpä demoni.wav",
// "sounds/seppo/ehkäpä.wav",
// "sounds/seppo/eihaittaa demoni.wav",
// "sounds/seppo/eikapineestamitäähaittaa.wav",
// "sounds/seppo/eikiitos.wav",
// "sounds/seppo/eikukaahuomaistakahuoneest.wav",
// "sounds/seppo/eisenintohimontarvitsekadota.wav",
// "sounds/seppo/eituuminkäälaistahajua.wav",
// "sounds/seppo/eivoimääräillämitämäomassakodis.wav",
// "sounds/seppo/elina.wav",
// "sounds/seppo/elinaeisaavihjettäharrastus.wav",
// "sounds/seppo/elinaisaa demoni.wav",
// "sounds/seppo/enpäootulluajatelleeks.wav",
// "sounds/seppo/entästääpomos.wav",
// "sounds/seppo/eteeshäpee - puhelin.wav",
// "sounds/seppo/eteeshäpee.wav",
// "sounds/seppo/etvoiollatosissas.wav",
// "sounds/seppo/hienohomma - puhelin.wav",
// "sounds/seppo/hienohomma.wav",
// "sounds/seppo/hienoltanäyttää.wav",
// "sounds/seppo/hiivaa.wav",
// "sounds/seppo/ismolopeta.wav",
// "sounds/seppo/jahyväätulloo.wav",
// "sounds/seppo/jajossatuomoasuu.wav",
// "sounds/seppo/jaksatsä.wav",
// "sounds/seppo/jasiinäilmotuksessaolevaannumeroonvastaatsinä.wav",
// "sounds/seppo/jasitäpaitsivielävarastaakki.wav",
// "sounds/seppo/joltaiasiakkaaltaaikanaan.wav",
// "sounds/seppo/jonkasinäomistat.wav",
// "sounds/seppo/josoisinsaanukaataaastiaan.wav",
// "sounds/seppo/josvaikkapinoit.wav",
// "sounds/seppo/kappaslikkaakutunnistit.wav",
// "sounds/seppo/kari.wav",
// "sounds/seppo/karvanen.wav",
// "sounds/seppo/kas niiin.wav",
// "sounds/seppo/katosnytätätäkikaunotarta.wav",
// "sounds/seppo/kaupungissa.wav",
// "sounds/seppo/keittelydemoni 2.wav",
// "sounds/seppo/keittelydemoni.wav",
// "sounds/seppo/kengänkuva perusuksiin.wav",
// "sounds/seppo/kiitoskumuist.wav",
// "sounds/seppo/kiitoskumuistutit - puhelin.wav",
// "sounds/seppo/kiitoskumuistutitmua.wav",
// "sounds/seppo/kiree demoni.wav",
// "sounds/seppo/kirjotankoettäkirstille.wav",
// "sounds/seppo/kohtakartano demoni.wav",
// "sounds/seppo/kohtatäälläelelläänkukartanos - puhelin.wav",
// "sounds/seppo/kohtatäälläelelläänkukartanos.wav",
// "sounds/seppo/koitanytrauho.wav",
// "sounds/seppo/kristo.wav",
// "sounds/seppo/kyllätännemahtuu.wav",
// "sounds/seppo/kyltämätulijoselväks.wav",
// "sounds/seppo/kärisvällisyysnäissäpuuhissa.wav",
// "sounds/seppo/liikakilo.wav",
// "sounds/seppo/luritetaanlitkupulloon.wav",
// "sounds/seppo/mehumaija.wav",
// "sounds/seppo/mennäääkeittiöön.wav",
// "sounds/seppo/minkätakiasäootniinkiree.wav",
// "sounds/seppo/minäasun.wav",
// "sounds/seppo/minäoonherrratalossa.wav",
// "sounds/seppo/minäyritänmurtautuapuustiselle.wav",
// "sounds/seppo/mitenelinastaontullukomentelija.wav",
// "sounds/seppo/mitenvoiollamahollista.wav",
// "sounds/seppo/mitä helkkaria.wav",
// "sounds/seppo/mitähitaammintippuusenparempi.wav",
// "sounds/seppo/mitäsmätämmöstäselitän.wav",
// "sounds/seppo/mitässanot - puhelin.wav",
// "sounds/seppo/mitässanot.wav",
// "sounds/seppo/mitätoinyton.wav",
// "sounds/seppo/mullonsiitähuonojakokemuksia.wav",
// "sounds/seppo/munhantämäasuntoon.wav",
// "sounds/seppo/mustaherukkamehuu.wav",
// "sounds/seppo/mäkannanomaanmakuuhuoneesee.wav",
// "sounds/seppo/mäkätätkomenteletmääräilet.wav",
// "sounds/seppo/mätuonomaankotiini.wav",
// "sounds/seppo/nettionhävinny - puhelin.wav",
// "sounds/seppo/nii.wav",
// "sounds/seppo/niionjaottanulisäävelkaa.wav",
// "sounds/seppo/noeitäähaiseyhtää.wav",
// "sounds/seppo/nohyväon.wav",
// "sounds/seppo/noistsarjakuvalehist.wav",
// "sounds/seppo/nojjuujuusentakiamäaionputsatane.wav",
// "sounds/seppo/nokatotaanytmistämikäki.wav",
// "sounds/seppo/nomitenvaanenpysty.wav",
// "sounds/seppo/noniinpäniiukinröllityttö.wav",
// "sounds/seppo/nosanotaankonytnäin - puhelin.wav",
// "sounds/seppo/nosanotaankonytnäin.wav",
// "sounds/seppo/nytpannusisäänjäinsittekiinni.wav",
// "sounds/seppo/näillekilöytyykerä.wav",
// "sounds/seppo/näistäarvotavaroistaälähulluja.wav",
// "sounds/seppo/näätavaratsaaviho.wav",
// "sounds/seppo/oikeinvalmistettunahajutonta.wav",
// "sounds/seppo/olehyväjapoistu.wav",
// "sounds/seppo/olimitenolimut.wav",
// "sounds/seppo/olisuksetristissäpahastik.wav",
// "sounds/seppo/omaaisääkinmäärääku.wav",
// "sounds/seppo/omassakodissasaantehämitähuvitt.wav",
// "sounds/seppo/onnillaontoinen.wav",
// "sounds/seppo/osaanvaranipitää.wav",
// "sounds/seppo/pakettihiivaa - puhelin.wav",
// "sounds/seppo/pakettihiivaa.wav",
// "sounds/seppo/pakkaatavarasheti.wav",
// "sounds/seppo/pakttihiivaa pitkä.wav",
// "sounds/seppo/paraskinpuhumaan - puhelin.wav",
// "sounds/seppo/paraskinpuhumaan.wav",
// "sounds/seppo/parempivaankupäätyvät.wav",
// "sounds/seppo/paskaa.wav",
// "sounds/seppo/pelkkäharrastus.wav",
// "sounds/seppo/perrrhana - puhelin.wav",
// "sounds/seppo/perrrhana.wav",
// "sounds/seppo/perrrrrrrrrrrrr2r.wav",
// "sounds/seppo/perrrrrrrrrrrrrr.wav",
// "sounds/seppo/persuksiin.wav",
// "sounds/seppo/pidetäätääpannuhommameidänsalaisuutena.wav",
// "sounds/seppo/pullo pankolle.wav",
// "sounds/seppo/pullo.wav",
// "sounds/seppo/putsata demoni.wav",
// "sounds/seppo/pysähdypentele.wav",
// "sounds/seppo/päiväähauskatutustua - puhelin.wav",
// "sounds/seppo/päiväähauskatutustua.wav",
// "sounds/seppo/pöllitsäkihlasormuksen.wav",
// "sounds/seppo/rahantuloa ei voi estää.wav",
// "sounds/seppo/reittiselvä.wav",
// "sounds/seppo/ryminää - puhelin.wav",
// "sounds/seppo/ryminää.wav",
// "sounds/seppo/saadaavähäuuttailmettätähäkki.wav",
// "sounds/seppo/saankohuomaut demoni.wav",
// "sounds/seppo/saankohuomauttaa.wav",
// "sounds/seppo/saisitsinäkiosas.wav",
// "sounds/seppo/samallatisleet demoni.wav",
// "sounds/seppo/samallatuleehyvättisleet.wav",
// "sounds/seppo/se oli kalliski.wav",
// "sounds/seppo/sekapineeioosuntiellä.wav",
// "sounds/seppo/selittelemään demoni.wav",
// "sounds/seppo/seppotaalasmaa - puhelin.wav",
// "sounds/seppo/seppotaalasmaa.wav",
// "sounds/seppo/sielläsaisitmääräillä.wav",
// "sounds/seppo/siitäonmyyntiilmotusnetissä.wav",
// "sounds/seppo/siitässait.wav",
// "sounds/seppo/siitätekijällepaljoniloa.wav",
// "sounds/seppo/silläsiisti.wav",
// "sounds/seppo/sinämäkätätjamääräilet.wav",
// "sounds/seppo/sitäpaitsi - puhelin.wav",
// "sounds/seppo/sitäpaitsi.wav",
// "sounds/seppo/sokeriakuutisenkiloa.wav",
// "sounds/seppo/suonikohju.wav",
// "sounds/seppo/suonikohjutaimuutamaliikakilo.wav",
// "sounds/seppo/syön.wav",
// "sounds/seppo/sä et vaikuta innokkaalta.wav",
// "sounds/seppo/säootfiksu demoni.wav",
// "sounds/seppo/säootfiksutyttö.wav",
// "sounds/seppo/taimuutama.wav",
// "sounds/seppo/takahuonees huomais.wav",
// "sounds/seppo/tekaikkiasuttemunasunnos.wav",
// "sounds/seppo/telkkarionhävinny.wav",
// "sounds/seppo/tervemenoa - puhelin.wav",
// "sounds/seppo/tervemenoatämäpannumuutti.wav",
// "sounds/seppo/tuletkosinäminullevaimoks - puhelin.wav",
// "sounds/seppo/tuletkosinäminullevaimoks.wav",
// "sounds/seppo/tuskinelinakaasinnekurkkii.wav",
// "sounds/seppo/tylsäämeilläeiollukoskaakeskenämme.wav",
// "sounds/seppo/tärkeintäonpuuhailu.wav",
// "sounds/seppo/tääalakaappionparempi.wav",
// "sounds/seppo/tääkaappionollukäyttämättävuosikausia.wav",
// "sounds/seppo/täälläseonturvassaniinelinaltaku.wav",
// "sounds/seppo/ullaa.wav",
// "sounds/seppo/ullanäistäainamotkotti.wav",
// "sounds/seppo/vaarallisenpaljonalatkuulostaaäidiltäs - puhelin.wav",
// "sounds/seppo/vaarallisenpaljonalatkuulostaaäidiltäs.wav",
// "sounds/seppo/vaiknytonmuutama.wav",
// "sounds/seppo/vaiknytonmuutamasuonikohju - puhelin.wav",
// "sounds/seppo/vaiknytonmuutamasuonikohju.wav",
// "sounds/seppo/vaintaivasonrajana.wav",
// "sounds/seppo/vastaamullerehellisesti.wav",
// "sounds/seppo/voisaakeli - puhelin.wav",
// "sounds/seppo/voisaakeli demoni.wav",
// "sounds/seppo/voisaakelitätäelämää.wav",
// "sounds/seppo/voisitsäpitääjotaiääntä.wav",
// "sounds/seppo/yhenpalveluksenpyytäisin -puhelin.wav",
// "sounds/seppo/yhenpalveluksenpyytäisin.wav",
// "sounds/seppo/äläsiinäselittelemäänsäootkiinni.wav",
// "sounds/seppo/äläsärupeenoihihommii.wav"]);

// Salkkarit.Models.soundPathCollections.push([
// "sounds/seppo2/aha.wav",
// "sounds/seppo2/aika suoraa puhetta.wav",
// "sounds/seppo2/eestä ja takaa.wav",
// "sounds/seppo2/ehkä sun ois paras mennä kotiin.wav",
// "sounds/seppo2/en anna pontikkaa sulle.wav",
// "sounds/seppo2/en minä tiedä.wav",
// "sounds/seppo2/hei haloo haloo ois yks kysymys haloo.wav",
// "sounds/seppo2/hei mitä sä niitä kamppeita tänne raahaat kellariinhan ne pitää viedä.wav",
// "sounds/seppo2/Herra insinööri on sitten hyvä ja hakee muualta töitä.wav",
// "sounds/seppo2/huoltolaskusta.wav",
// "sounds/seppo2/illan emännälle.wav",
// "sounds/seppo2/isabella.wav",
// "sounds/seppo2/jaa näyttäkääpäs miten.wav",
// "sounds/seppo2/jonkun tyttölapsenko kanssa sä juttelet.wav",
// "sounds/seppo2/Joo nii varmaa.wav",
// "sounds/seppo2/joo se oli.wav",
// "sounds/seppo2/joo varmasti ne on kyllä hienon näkösiä.wav",
// "sounds/seppo2/joo.wav",
// "sounds/seppo2/Jos kaadutaan ni kaadutaan ykköset pääl.wav",
// "sounds/seppo2/Jos toi asia vaivaa sua niin kovasti niin kerro Lasselle koko juttu.wav",
// "sounds/seppo2/jälkiruokapalleroitakin.wav",
// "sounds/seppo2/Kato se muisti.wav",
// "sounds/seppo2/Ken liekin sammuttaa.wav",
// "sounds/seppo2/Kiitos, resepti oli siinä makkarapaketin kyljessä.wav",
// "sounds/seppo2/Kiitos.wav",
// "sounds/seppo2/kristo päivinen.wav",
// "sounds/seppo2/kukaan ei vastaa puhelimeen väki vaihtuu.wav",
// "sounds/seppo2/Kyllä meidän täytyy soittaa poliisille.wav",
// "sounds/seppo2/lesbot ja homot.wav",
// "sounds/seppo2/lihapullia ja muusia.wav",
// "sounds/seppo2/Meil on tääl yks vieras.wav",
// "sounds/seppo2/mies.wav",
// "sounds/seppo2/Minulla on ilmoitusasia.wav",
// "sounds/seppo2/Minä olen tässä perheessä vanhin ja minä määrään täällä.wav",
// "sounds/seppo2/Missäs maailmassa sinä olit.wav",
// "sounds/seppo2/Mistä lähtien sä oot ruvennu.wav",
// "sounds/seppo2/mitähän se tarkottaa.wav",
// "sounds/seppo2/mitäs ne pitää niinku sisällään.wav",
// "sounds/seppo2/Mua epäillään huumeiden hallussapidosta ja välittämisestä.wav",
// "sounds/seppo2/mun kokemuksen mukaa naisväki.wav",
// "sounds/seppo2/Mutta sinä annoit meidän syyttää väärää miestä.wav",
// "sounds/seppo2/Mä kävin tässä tunti sitten ni ovi oli kiinni.wav",
// "sounds/seppo2/Mähän oon tavallinen kaduntallaaja.wav",
// "sounds/seppo2/Nii.wav",
// "sounds/seppo2/no erottuuhan joukost.wav",
// "sounds/seppo2/no mitäs outoo siinä on.wav",
// "sounds/seppo2/No ota se siitä nyt kun se kerran siinä o.wav",
// "sounds/seppo2/No pitikö sun ruveta koisimaan ku sun piti vahtia tyttöö.wav",
// "sounds/seppo2/No älä sinä siinä, tule ite leipomaan.wav",
// "sounds/seppo2/nytkö.wav",
// "sounds/seppo2/On, ja kovasti on murheellisen näköne.wav",
// "sounds/seppo2/Onks Lasse.wav",
// "sounds/seppo2/ootko seonnu.wav",
// "sounds/seppo2/Pikkupojasta asti.wav",
// "sounds/seppo2/se oli onneton sattuma.wav",
// "sounds/seppo2/Se vaahtos muuten helvetin huonosti.wav",
// "sounds/seppo2/Sepin ja Karin kännilaulu.wav",
// "sounds/seppo2/Seppo - Ammuskelun seurauksena tää Sege halvaantu ja se uhkas tappaa sekä Roomeon että Rafaelin.wav",
// "sounds/seppo2/Seppo - Ei kai niille käyny kuinkaan.wav",
// "sounds/seppo2/Seppo - Ei kannata antaa periks jos on vastatuulta.wav",
// "sounds/seppo2/Seppo - Et kai sä tosissas muuta kuvitellu.wav",
// "sounds/seppo2/Seppo - Et ollenkaan.wav",
// "sounds/seppo2/Seppo - Hei Paula katos kuka täällä on.wav",
// "sounds/seppo2/Seppo - Helena huhuu, oot sä kotona.wav",
// "sounds/seppo2/Seppo - Iltaa itse kullekkin säädylle.wav",
// "sounds/seppo2/Seppo - Ismo muutti meille.wav",
// "sounds/seppo2/Seppo - Jos et veikkaa et voi voittaa.wav",
// "sounds/seppo2/Seppo - Kai te käytätte kondomia.wav",
// "sounds/seppo2/Seppo - Kallee ja Miiaakin mukiloit mennen tullen.wav",
// "sounds/seppo2/Seppo - Kari.wav",
// "sounds/seppo2/Seppo - Koston kierre sen kun jatkuu ja jatkuu.wav",
// "sounds/seppo2/Seppo - Kostosuunnitelmaa.wav",
// "sounds/seppo2/Seppo - Kumpaakohan sä nyt oikein enemmän ajattelet. Nooraa vai ittees.wav",
// "sounds/seppo2/Seppo - Kuule nyt istut alas, mä keitän sulle teetä.wav",
// "sounds/seppo2/Seppo - Kyllä pystyt.wav",
// "sounds/seppo2/Seppo - Kyllä se Ismo on nyt niin että meikäläinen on tullu pahemman kerran huijatuks.wav",
// "sounds/seppo2/Seppo - Mene nyt suihkuun tai tee jotain.wav",
// "sounds/seppo2/Seppo - Miks mä ylipäätään tänne tulinkaan.wav",
// "sounds/seppo2/Seppo - Minkä ihmeen takia.wav",
// "sounds/seppo2/Seppo - Minkä takia.wav",
// "sounds/seppo2/Seppo - Missä ne särkylääkkeet nyt on.wav",
// "sounds/seppo2/Seppo - Missäs sun työhaalarit o.wav",
// "sounds/seppo2/Seppo - Mistä sä tommosta oot keksiny.wav",
// "sounds/seppo2/Seppo - Mitä ihmettä (Sepi löysi Nallekarkit).wav",
// "sounds/seppo2/Seppo - Mitä oot sä juovuksissa keskellä työpäivää.wav",
// "sounds/seppo2/Seppo - Mitäs täällä tapahtuu.wav",
// "sounds/seppo2/Seppo - Mun olis heti pitäny arvata ku Tanja kävi kertomassa siitä sun väkivaltasesta käytöksestä.wav",
// "sounds/seppo2/Seppo - Mä en usko sua.wav",
// "sounds/seppo2/Seppo - Mä soitan ambulanssin.wav",
// "sounds/seppo2/Seppo - Mä tarjoon pizzat kaikille sovinnon kunniaks.wav",
// "sounds/seppo2/Seppo - Mä tosiaan luulin että sä olisit oppinu virheistäs mutta ei.wav",
// "sounds/seppo2/Seppo - Niin ku teillä on vielä Ismo siellä nurkissa.wav",
// "sounds/seppo2/Seppo - Niin mäkin sua.wav",
// "sounds/seppo2/Seppo - No eikän noora kuuro oo kyllähän se kuulee vähemmälläkin.wav",
// "sounds/seppo2/Seppo - No konjakkihan tekee flunssaan justiin hyvää.wav",
// "sounds/seppo2/Seppo - No miten se, miten se nyrkki sitten vaan heiluu.wav",
// "sounds/seppo2/Seppo - No mitä, pitäiskö tässä selkään taputella.wav",
// "sounds/seppo2/Seppo - No sehän sopii niin saadaan tämäkin homma pois päiväjärjestyksestä.wav",
// "sounds/seppo2/Seppo - No tossa Paulan kanssa törmätessä ei muusta puhuttukkaan.wav",
// "sounds/seppo2/Seppo - No voi hemmetti, hemmetin hemmetti.wav",
// "sounds/seppo2/Seppo - No voi hemmetti.wav",
// "sounds/seppo2/Seppo - No voi pahus ja mä unohdin laittaa toisen akun lataukseen.wav",
// "sounds/seppo2/Seppo - Nyt on piru merrassa, naapuritalos on taas hajonu putki.wav",
// "sounds/seppo2/Seppo - Oi kun on hyvän näkösiä.wav",
// "sounds/seppo2/Seppo - Olen olen.wav",
// "sounds/seppo2/Seppo - Onko sulla Oona joku vialla.wav",
// "sounds/seppo2/Seppo - Oona ja jopa meidän Kari katso koko ohjelman alusta loppuun asti ja vielä pitivät siitä.wav",
// "sounds/seppo2/Seppo - Pilasit Roomeon elämän.wav",
// "sounds/seppo2/Seppo - Poliisi epäilee että se nyt ois lähteny sinne ulkomaille.wav",
// "sounds/seppo2/Seppo - Rikos mikä rikos.wav",
// "sounds/seppo2/Seppo - Senkö takia sä purit teidän kihlauksen.wav",
// "sounds/seppo2/Seppo - Sepi tässä taas hei.wav",
// "sounds/seppo2/Seppo - Seppo Taalasmaa.wav",
// "sounds/seppo2/Seppo - Seppo Taalasmaa2.wav",
// "sounds/seppo2/Seppo - Soitatko heti kun saat tän viestin, mä oon jo vähän huolissani.wav",
// "sounds/seppo2/Seppo - Susta on riesaa aina vaan.wav",
// "sounds/seppo2/Seppo - Sä et ole oikein hyvä puhumaan näistä asioista.wav",
// "sounds/seppo2/Seppo - Teidän suhde on vielä pelastettavissa.wav",
// "sounds/seppo2/Seppo - Tules poika sinäkin ottamaan hiukopalaa ni sinäkin jaksat tehdä töitä.wav",
// "sounds/seppo2/Seppo - Tuli asiaa.wav",
// "sounds/seppo2/Seppo - Tuon viisaanpaa päätöstä et ois voinu tehä (Ipi kertoi Sepille lyöneensä Juuliaa).wav",
// "sounds/seppo2/Seppo - Täytyy sanoo että niin minunki.wav",
// "sounds/seppo2/Seppo - Töihin nyt siitä.wav",
// "sounds/seppo2/Seppo - Varmaan joku väärinkäsitys.wav",
// "sounds/seppo2/taivaan portilla.wav",
// "sounds/seppo2/telkkari videot taulu.wav",
// "sounds/seppo2/Tommost pippurijuustoo ja arvaa mitä kuule, olutta.wav",
// "sounds/seppo2/totta helvetissä juon ku ilmasiks saa.wav",
// "sounds/seppo2/Tuohan nyt kuulostaa ihan normaalilta.wav",
// "sounds/seppo2/Tällä tavallaks sun edellisessä työpaikassa toimittiin.wav",
// "sounds/seppo2/Täs ois tällänen tyyny.wav",
// "sounds/seppo2/tää kauppa on suljettu.wav",
// "sounds/seppo2/Vai onks se liian littana sulle.wav",
// "sounds/seppo2/Yhdet vaan otettiin.wav",
// "sounds/seppo2/äitis.wav",
// "sounds/seppo2/Älä höpise, näistä tulee kuule kaikkienaikojen sämpylät.wav",
// "sounds/seppo2/älä marise itehän sen kanssa aloit vehtaamaan.wav",
// "sounds/seppo2/Älä nyt koske ku semmone.wav",
// "sounds/seppo2/Älä nyt koske.wav",
// "sounds/seppo2/Älä nyt sinäkin enää sekaannu tähän.wav",
// "sounds/seppo2/älä pane niitä jalkoja pöydälle.wav"]);

// Salkkarit.Models.soundPathCollections.push([
// "sounds/sofia/haistahome.wma",
// "sounds/sofia/ihanaa.wma",
// "sounds/sofia/kiitti.wav",
// "sounds/sofia/mikätääniikuon.wma",
// "sounds/sofia/mitäteoikeenmeinaatte.wma",
// "sounds/sofia/mä en uskaltanu ite ostaa ku.wav",
// "sounds/sofia/mä tapaan mun poikaystävän.wav",
// "sounds/sofia/niko.wma",
// "sounds/sofia/paska.wma",
// "sounds/sofia/paskapuhetta.wma",
// "sounds/sofia/pidetäänsithauskaa.wma",
// "sounds/sofia/sankari.wma",
// "sounds/sofia/sidukkaataijotainmieluummin.wma",
// "sounds/sofia/Sofia - Helenan poika hyökkäs aseen kanssa Rafaelin kimppuun ja Rafael ampu sitä vahingossa.wav",
// "sounds/sofia/Sofia - Kato nyt mitä sä teit.wav",
// "sounds/sofia/Sofia - Ku ei se voinu muuta, ja meinasin sitäpaitsi lähteä viel niiden mukaan.wav",
// "sounds/sofia/Sofia - Mummi nyt kuuntele.wav",
// "sounds/sofia/Sofia - Mummi, mä en haluis et sä oot surullinen.wav",
// "sounds/sofia/Sofia - Ne lähti pois suomesta Rafaelin ja Maijan kanssa.wav",
// "sounds/sofia/Sofia - No kai se elää, ainakin se vanno kostavansa.wav",
// "sounds/sofia/Sofia - Onks siinä mitään tolkkua.wav",
// "sounds/sofia/Sofia - Roomeo!.wav",
// "sounds/sofia/Sofia - Roomeo.wav",
// "sounds/sofia/sä et vaan haluu mua.wma",
// "sounds/sofia/Sänkyyn!.wma",
// "sounds/sofia/sänkyyn.wav",
// "sounds/sofia/teootteniinsäälittäviä.wma",
// "sounds/sofia/tosikivaa.wma",
// "sounds/sofia/tätämäjusttarviin.wma"]); 

// Salkkarit.Models.soundPathCollections.push([
// "sounds/spuge/eiköhä katota.wav",                   "haluutko huikan.wav",
// "sounds/spuge/joojoo ettei tuu sanomista.wav",      "josseurakelpaa.wav",
// "sounds/spuge/juujuuniinpänii.wav",                 "missä meinaat juoda putelis.wav",
// "sounds/spuge/mitä likka.wav",                      "mitähelvettiä.wav",
// "sounds/spuge/muistakaa nussia.wav",                "nimittäin tätä.wav",
// "sounds/spuge/no nii muute minäki.wav",             "noh.wav",
// "sounds/spuge/noh2.wav",                            "pitäähän naista auttaa mäessä.wav",
// "sounds/spuge/päästää nukkumaanki joskus.wav",      "räkäset naurut 2.wav",
// "sounds/spuge/räkäset naurut.wav",                  "räkäset naurut3.wav",
// "sounds/spuge/tulee taatusti parempi mieli.wav"]);

// Salkkarit.Models.soundPathCollections.push([
// "sounds/tanja/ainiimähaenpyyhkeen.wav",
// "sounds/tanja/ei missää nimes tää on tarpeeks kamalaa ilman poliisejaki.wav",
// "sounds/tanja/Eli tästä eteenpäin kaupan esimies on Noora ja sinä hänen alaisensa.wav",
// "sounds/tanja/entä jos mä maksan sille.wav",
// "sounds/tanja/et tietenkään oo.wav",
// "sounds/tanja/ismo.wav",
// "sounds/tanja/ismo2.wav",
// "sounds/tanja/ismo3.wav",
// "sounds/tanja/ismo4.wav",
// "sounds/tanja/ismoa.wav",
// "sounds/tanja/ISMOH.wav",
// "sounds/tanja/julia on meiän toimistoapulainen.wav",
// "sounds/tanja/julia tarkotti pelkkää hyvää myös teidän kannaltanne.wav",
// "sounds/tanja/juliah.wav",
// "sounds/tanja/juulia autio.wav",
// "sounds/tanja/katsotaan kuitenkin meidän näitä muita kohteita.wav",
// "sounds/tanja/kiitos ossi.wav",
// "sounds/tanja/Kuullostaa hyvältä.wav",
// "sounds/tanja/kyllä tää nyt paris päiväs ohi menee.wav",
// "sounds/tanja/lohipiirakka.wav",
// "sounds/tanja/Lähde ole hyvä.wav",
// "sounds/tanja/me tehään ossin kanssa.wav",
// "sounds/tanja/mee pois mun kodista.wav",
// "sounds/tanja/Meidän täytyy ostaa sulle kunnon sänky.wav",
// "sounds/tanja/mihin.wav",
// "sounds/tanja/Mikä sun ajatukset sai muuttumaan.wav",
// "sounds/tanja/Minkä takia.wav",
// "sounds/tanja/miten maksat takas.wav",
// "sounds/tanja/Mitää.wav",
// "sounds/tanja/moraalia.wav",
// "sounds/tanja/Mul on lohipiirakka tuolla jääkaapissa.wav",
// "sounds/tanja/mul on vatsatauti.wav",
// "sounds/tanja/mun rahojani.wav",
// "sounds/tanja/munkin.wav",
// "sounds/tanja/Must on ihanaa että sä oot täällä.wav",
// "sounds/tanja/mut ilmeisesti työnkuva ei ollu tarpeeks haasteellinen.wav",
// "sounds/tanja/mä oon pahoillani mut me ei voida ottaa teiän tarjousta vastaan.wav",
// "sounds/tanja/mä pyydän että sä suostut.wav",
// "sounds/tanja/mä ärsytin ismoo.wav",
// "sounds/tanja/nii.wav",
// "sounds/tanja/No ei nyt Ismo ampuis ketään.wav",
// "sounds/tanja/No on se kuitenkin jotain ja loput maksan kuitenkin minä.wav",
// "sounds/tanja/nyt lopetat ton.wav",
// "sounds/tanja/Oi kauheeta.wav",
// "sounds/tanja/oi kauheeta2.wav",
// "sounds/tanja/olihan sillä syynsä.wav",
// "sounds/tanja/Oot sä varmasti ratsastuskunnossa.wav",
// "sounds/tanja/ossi.wav",
// "sounds/tanja/ossi2.wav",
// "sounds/tanja/ossilla oli hirveen.wav",
// "sounds/tanja/Painu ulos täältä.wav",
// "sounds/tanja/paljon vaivaa.wav",
// "sounds/tanja/poliiseja.wav",
// "sounds/tanja/rakkavaaran osakkeita.wav",
// "sounds/tanja/ruokaa.wav",
// "sounds/tanja/saatavilla.wav",
// "sounds/tanja/sain.wav",
// "sounds/tanja/Se oli vahinko.wav",
// "sounds/tanja/sillä tavalla sulle eikä firmalle koidu vahinkoa.wav",
// "sounds/tanja/sinä ja ossi ootte käsittäny väärin.wav",
// "sounds/tanja/sulla ei oo oikeuksia myydä asuntoja.wav",
// "sounds/tanja/sä et voi jatkaa enää happy homesissa edes apulaisena.wav",
// "sounds/tanja/sä oot mies jolle ei voi.wav",
// "sounds/tanja/Sä oot nyt ihan eri ihminen ku aamulla.wav",
// "sounds/tanja/sä raiskasit mut.wav",
// "sounds/tanja/Tavallaan mitä sä oikein salailet.wav",
// "sounds/tanja/Tuuraan Ismoa.wav",
// "sounds/tanja/tänkunniaks.wav",
// "sounds/tanja/töissä.wav",
// "sounds/tanja/Vittu.wav",
// "sounds/tanja/ymmärsit sä mitä täst voi seurata.wav",
// "sounds/tanja/Älä enää ikinä tee tällä tavalla.wav",
// "sounds/tanja/Älä pelottele mua.wav"]); 

// Salkkarit.Models.soundPathCollections.push([
// "sounds/tuomo/apuvoimat on tulos.wav",
// "sounds/tuomo/eiooaikaajauhaapaskaa.wav",
// "sounds/tuomo/en.wav",
// "sounds/tuomo/haistapaska.wav",
// "sounds/tuomo/ja sit sä lasket aseen.wav",
// "sounds/tuomo/kaksi.wav",
// "sounds/tuomo/minä olen.wav",
// "sounds/tuomo/mä lasken kolmee.wav",
// "sounds/tuomo/paska.wav",
// "sounds/tuomo/poliisi laske se ase.wav",
// "sounds/tuomo/stuba pistä se ase maaha.wav",
// "sounds/tuomo/sä et pääse karkuun anna sen pojan mennä.wav",
// "sounds/tuomo/tuomo-avaimet.wav",
// "sounds/tuomo/tuomo-heivoitsäkattoonnii.wav",
// "sounds/tuomo/tuomo-joo.wav",
// "sounds/tuomo/tuomo-joo2.wav",
// "sounds/tuomo/tuomo-lähtikuitenki.wav",
// "sounds/tuomo/tuomo-löysinhänmäsut.wav",
// "sounds/tuomo/tuomo-munpitäispäästäkäymääteil.wav",
// "sounds/tuomo/tuomo-mähaluisinjotenki.wav",
// "sounds/tuomo/tuomo-mätiiän.wav",
// "sounds/tuomo/tuomo-nii.wav",
// "sounds/tuomo/tuomo-nojosmänytvähä.wav",
// "sounds/tuomo/tuomo-nyt.wav",
// "sounds/tuomo/tuomo-olikssullatreenit.wav",
// "sounds/tuomo/tuomo-tykkäätsäteatterista.wav",
// "sounds/tuomo/tuomo-töihi.wav",
// "sounds/tuomo/tuomo-äläyhtäävirnuile.wav",
// "sounds/tuomo/yksi.wav"]); 